name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build project
      run: pnpm run build

    - name: Check for dist changes
      id: dist-changes
      run: |
        git add dist
        if git diff --cached --quiet; then
          echo "dist_changed=false" >> $GITHUB_OUTPUT
        else
          echo "dist_changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push changes
      if: steps.dist-changes.outputs.dist_changed == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git commit -m "chore: update dist files [skip ci]"
        git push
